[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['cd template-bot && pnpm install']

[phases.build]
cmds = ['cd template-bot && pnpm build']

[start]
cmd = 'cd template-bot && pnpm start'
