version: "3"
output: interleaved
dotenv: [".env.local"]

tasks:
  post_create:
    desc: "Runs after this template is instantiated as a Sandbox or Bootstrap"
    cmds:
      - echo -e "To setup and run the agent:\r\n"
      - echo -e "    cd {{.ROOT_DIR}}\r"
      - echo -e "    pnpm install\r"
      - echo -e "    pnpm build\r"
      - echo -e "    node dist/agent.js dev\r\n"

  install:
    desc: "Bootstrap application for local development"
    cmds:
      - "pnpm install"
